favicon: /assets/images/favicon.png
search-label: MorelloProject
name: MorelloProject
# slogan: Open Source Secure World Software
# Breadcrumb Settings
breadcrumb:
  page-titles: false
# Used for the edit on github include
edit-on-github:
    enabled: false
    repo: https://github.com/MorelloProject/website
# Mailchimp settings
mailchimp:
    enabled: false
# Footer Newsletter toggle.
newsletter:
    enabled: false
# Blog tags
tags_enabled: true
# Jekyll social media site settings. Github, LinkedIn, Google+, Facebook and Youtube
github_username: OpenAMP
# Blog setup
blog:
    # Toggle site wide comments display.
    comments: false
    # Post Side Bar Settings
    sidebar:
        # Toggle whether or not thumbnails in the sidebar are displayed.
        thumbnails:
            display: true
        # Display other posts contained in _posts
        other-posts:
            display: true
            count: 4
        # Display Related posts based on tags / categories
        related-posts:
            display: true
            count: 5
        # Display the most recent posts
        most-recent-posts:
            display: true
            count: 5
# Google Anayltics Setup
google_analytics:
  production: UA-16756069-34
# Shema.org settings used in the schema.html include.
schema:
    enabled: false
    organisation:
        name: MorelloProject
        url: https://morello-project.org
        address:
            street: Harston Mill, Royston Rd
            town: Harston
            county: Cambridge
            post_code: CB22 7GG
            country_code: UK
# Disqus Comments
disqus:
    enabled: false
    shortname: morelloproject
# Placeholder for Missing Images
placeholder: /assets/images/content/morello-project.png
social_media_channels:
  - https://github.com/MorelloProject

github_username: MorelloProject
linkedin_username: false
facebook_username: false
youtube_username: false
twitter_username: false
